// ParaliPay Resilient Mock & Demo Dataset
// Used for standalone frontend hosting (e.g., Vercel, Netlify) when the backend is offline or unlinked

export const MOCK_FARMER_USER = {
  id: 1,
  full_name: "Harmanpreet Singh Brar",
  email: "e2e_farmer@punjab.in",
  phone: "+91 98150 24680",
  role: "FARMER",
  farmer_profile: {
    state: "Punjab",
    district: "Ludhiana",
    village: "Jagraon",
    latitude: 30.7850,
    longitude: 75.4780
  }
};

export const MOCK_BUYER_USER = {
  id: 2,
  full_name: "Vikramaditya Singhania",
  email: "e2e_buyer@biomassenergy.com",
  phone: "+91 98765 11223",
  role: "BUYER",
  buyer_profile: {
    business_name: "EverGreen Bio-Energy & CBG Plant Ltd",
    buyer_type: "Bio-CNG / CBG Plant",
    state: "Punjab",
    district: "Ludhiana",
    latitude: 30.9010,
    longitude: 75.8573,
    phone: "+91 98765 11223",
    preferred_material: "Paddy Straw Bales",
    required_quantity_tonnes: 6500.0,
    budget_per_tonne: 2350.0,
    verification_status: "VERIFIED",
    is_certified: true
  }
};

export const MOCK_MY_LISTINGS = [
  {
    id: 1,
    farmer_id: 1,
    farmer_name: "Harmanpreet Singh Brar",
    farmer_phone: "+91 98150 24680",
    quantity_tonnes: 380.0,
    asking_price_per_tonne: 2150.0,
    latitude: 30.7850,
    longitude: 75.4780,
    state: "Punjab",
    district: "Ludhiana",
    village: "Jagraon",
    crop: "Paddy (Rice)",
    residue_type: "Baled Straw",
    condition: "Dry",
    harvest_date: "2026-09-28",
    status: "AVAILABLE",
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    interest_count: 1
  }
];

export const MOCK_MY_INTERESTS = [
  {
    id: 1,
    listing_id: 1,
    buyer_id: 2,
    buyer_name: "Vikramaditya Singhania",
    buyer_business_name: "EverGreen Bio-Energy & CBG Plant Ltd",
    buyer_phone: "+91 98765 11223",
    crop: "Paddy (Rice)",
    quantity_tonnes: 380.0,
    message: "We have reviewed your 380 tonnes lot in Jagraon. We can deploy 4 semi-trailers starting this Monday. Gate price offered at ₹2,150/tonne.",
    status: "ACCEPTED",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString()
  }
];

export const MOCK_MY_CONTACTS = [
  {
    id: 1,
    farmer_id: 1,
    buyer_id: 2,
    buyer_name_ref: "EverGreen Bio-Energy & CBG Plant Ltd",
    message: "Sat Sri Akal Vikramaditya ji. We have 380 tonnes of dry, clean rectangular bales ready at our Jagraon farm. Full truck access available.",
    stubble_qty: 380.0,
    status: "ACCEPTED",
    is_read: true,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString()
  }
];

export const MOCK_ALL_LISTINGS = [
  {
    "id": 1,
    "farmer_id": 1,
    "farmer_name": "Harmanpreet Singh Brar",
    "farmer_phone": "+91 98150 24680",
    "quantity_tonnes": 380.0,
    "asking_price_per_tonne": 2150.0,
    "latitude": 30.785,
    "longitude": 75.478,
    "state": "Punjab",
    "district": "Ludhiana",
    "village": "Jagraon",
    "crop": "Paddy (Rice)",
    "residue_type": "Baled Straw",
    "condition": "Dry",
    "harvest_date": "2026-09-28",
    "status": "AVAILABLE",
    "created_at": "2026-10-04T08:30:00Z",
    "interest_count": 1
  },
  {
    "id": 2,
    "farmer_id": 3,
    "farmer_name": "Balwinder Singh Sidhu",
    "farmer_phone": "+91 98142 33411",
    "quantity_tonnes": 210.0,
    "asking_price_per_tonne": 1850.0,
    "latitude": 29.988,
    "longitude": 75.086,
    "state": "Punjab",
    "district": "Bathinda",
    "village": "Talwandi Sabo",
    "crop": "Cotton",
    "residue_type": "Cotton Stalks",
    "condition": "Dry",
    "harvest_date": "2026-10-02",
    "status": "AVAILABLE",
    "created_at": "2026-10-05T09:15:00Z",
    "interest_count": 1
  },
  {
    "id": 3,
    "farmer_id": 4,
    "farmer_name": "Gurdeep Singh Gill",
    "farmer_phone": "+91 98720 44522",
    "quantity_tonnes": 540.0,
    "asking_price_per_tonne": 1900.0,
    "latitude": 30.128,
    "longitude": 75.799,
    "state": "Punjab",
    "district": "Sangrur",
    "village": "Sunam",
    "crop": "Paddy (Rice)",
    "residue_type": "Loose Straw",
    "condition": "Semi-Dry",
    "harvest_date": "2026-10-05",
    "status": "AVAILABLE",
    "created_at": "2026-10-06T11:00:00Z",
    "interest_count": 1
  },
  {
    "id": 4,
    "farmer_id": 10,
    "farmer_name": "Sukhdev Singh Sandhu",
    "farmer_phone": "+91 98761 55211",
    "quantity_tonnes": 320.0,
    "asking_price_per_tonne": 2450.0,
    "latitude": 30.37,
    "longitude": 76.15,
    "state": "Punjab",
    "district": "Patiala",
    "village": "Nabha",
    "crop": "Wheat",
    "residue_type": "Wheat Straw (Turi)",
    "condition": "Dry",
    "harvest_date": "2026-09-15",
    "status": "AVAILABLE",
    "created_at": "2026-10-01T14:20:00Z",
    "interest_count": 0
  },
  {
    "id": 5,
    "farmer_id": 11,
    "farmer_name": "Paramjit Singh Randhawa",
    "farmer_phone": "+91 98155 44102",
    "quantity_tonnes": 360.0,
    "asking_price_per_tonne": 2200.0,
    "latitude": 31.84,
    "longitude": 74.76,
    "state": "Punjab",
    "district": "Amritsar",
    "village": "Ajnala",
    "crop": "Paddy (Rice)",
    "residue_type": "Baled Straw",
    "condition": "Dry",
    "harvest_date": "2026-10-01",
    "status": "AVAILABLE",
    "created_at": "2026-10-03T10:00:00Z",
    "interest_count": 0
  },
  {
    "id": 6,
    "farmer_id": 12,
    "farmer_name": "Karamjit Singh Virk",
    "farmer_phone": "+91 98722 88190",
    "quantity_tonnes": 185.0,
    "asking_price_per_tonne": 1800.0,
    "latitude": 31.125,
    "longitude": 75.472,
    "state": "Punjab",
    "district": "Jalandhar",
    "village": "Nakodar",
    "crop": "Maize",
    "residue_type": "Maize Stover",
    "condition": "Dry",
    "harvest_date": "2026-09-22",
    "status": "AVAILABLE",
    "created_at": "2026-09-29T16:45:00Z",
    "interest_count": 0
  },
  {
    "id": 7,
    "farmer_id": 13,
    "farmer_name": "Jagmohan Singh Dhillon",
    "farmer_phone": "+91 98144 77211",
    "quantity_tonnes": 420.0,
    "asking_price_per_tonne": 2180.0,
    "latitude": 30.97,
    "longitude": 74.98,
    "state": "Punjab",
    "district": "Firozpur",
    "village": "Zira",
    "crop": "Paddy (Rice)",
    "residue_type": "Baled Straw",
    "condition": "Dry",
    "harvest_date": "2026-10-03",
    "status": "AVAILABLE",
    "created_at": "2026-10-05T12:00:00Z",
    "interest_count": 1
  },
  {
    "id": 8,
    "farmer_id": 14,
    "farmer_name": "Kulwant Singh Grewal",
    "farmer_phone": "+91 98140 33888",
    "quantity_tonnes": 290.0,
    "asking_price_per_tonne": 2250.0,
    "latitude": 30.707,
    "longitude": 76.216,
    "state": "Punjab",
    "district": "Ludhiana",
    "village": "Khanna",
    "crop": "Paddy (Rice)",
    "residue_type": "Baled Straw",
    "condition": "Dry",
    "harvest_date": "2026-10-04",
    "status": "AVAILABLE",
    "created_at": "2026-10-06T09:30:00Z",
    "interest_count": 1
  },
  {
    "id": 9,
    "farmer_id": 15,
    "farmer_name": "Manjit Singh Dhaliwal",
    "farmer_phone": "+91 98725 66100",
    "quantity_tonnes": 240.0,
    "asking_price_per_tonne": 2500.0,
    "latitude": 30.68,
    "longitude": 75.08,
    "state": "Punjab",
    "district": "Moga",
    "village": "Baghapurana",
    "crop": "Wheat",
    "residue_type": "Wheat Straw (Turi)",
    "condition": "Dry",
    "harvest_date": "2026-09-18",
    "status": "AVAILABLE",
    "created_at": "2026-10-02T15:10:00Z",
    "interest_count": 0
  },
  {
    "id": 10,
    "farmer_id": 16,
    "farmer_name": "Harjinder Singh Chahal",
    "farmer_phone": "+91 98152 77332",
    "quantity_tonnes": 450.0,
    "asking_price_per_tonne": 2100.0,
    "latitude": 29.92,
    "longitude": 75.56,
    "state": "Punjab",
    "district": "Mansa",
    "village": "Budhlada",
    "crop": "Paddy (Rice)",
    "residue_type": "Baled Straw",
    "condition": "Dry",
    "harvest_date": "2026-10-02",
    "status": "AVAILABLE",
    "created_at": "2026-10-04T17:00:00Z",
    "interest_count": 0
  },
  {
    "id": 11,
    "farmer_id": 17,
    "farmer_name": "Satnam Singh Sekhon",
    "farmer_phone": "+91 98150 99441",
    "quantity_tonnes": 310.0,
    "asking_price_per_tonne": 1950.0,
    "latitude": 30.84,
    "longitude": 75.98,
    "state": "Punjab",
    "district": "Ludhiana",
    "village": "Sahnewal",
    "crop": "Paddy (Rice)",
    "residue_type": "Loose Straw",
    "condition": "Semi-Dry",
    "harvest_date": "2026-10-06",
    "status": "AVAILABLE",
    "created_at": "2026-10-07T08:00:00Z",
    "interest_count": 0
  },
  {
    "id": 12,
    "farmer_id": 18,
    "farmer_name": "Amarjit Singh Deol",
    "farmer_phone": "+91 98141 11200",
    "quantity_tonnes": 275.0,
    "asking_price_per_tonne": 1650.0,
    "latitude": 31.81,
    "longitude": 75.66,
    "state": "Punjab",
    "district": "Hoshiarpur",
    "village": "Dasuya",
    "crop": "Sugarcane",
    "residue_type": "Sugarcane Trash",
    "condition": "Dry",
    "harvest_date": "2026-09-26",
    "status": "AVAILABLE",
    "created_at": "2026-10-01T11:20:00Z",
    "interest_count": 0
  },
  {
    "id": 13,
    "farmer_id": 5,
    "farmer_name": "Rajinder Kumar Sharma",
    "farmer_phone": "+91 94161 22377",
    "quantity_tonnes": 480.0,
    "asking_price_per_tonne": 2350.0,
    "latitude": 29.833,
    "longitude": 76.92,
    "state": "Haryana",
    "district": "Karnal",
    "village": "Nilokheri",
    "crop": "Paddy (Rice)",
    "residue_type": "Baled Straw",
    "condition": "Dry",
    "harvest_date": "2026-10-03",
    "status": "AVAILABLE",
    "created_at": "2026-10-05T13:40:00Z",
    "interest_count": 1
  },
  {
    "id": 14,
    "farmer_id": 7,
    "farmer_name": "Chaudhary Ramphal Hooda",
    "farmer_phone": "+91 98120 33488",
    "quantity_tonnes": 340.0,
    "asking_price_per_tonne": 1650.0,
    "latitude": 28.831,
    "longitude": 76.398,
    "state": "Haryana",
    "district": "Rohtak",
    "village": "Kalanaur",
    "crop": "Sugarcane",
    "residue_type": "Sugarcane Trash",
    "condition": "Dry",
    "harvest_date": "2026-09-24",
    "status": "AVAILABLE",
    "created_at": "2026-09-30T10:15:00Z",
    "interest_count": 1
  },
  {
    "id": 15,
    "farmer_id": 19,
    "farmer_name": "Manjeet Singh Chahal",
    "farmer_phone": "+91 94163 88122",
    "quantity_tonnes": 290.0,
    "asking_price_per_tonne": 2150.0,
    "latitude": 30.03,
    "longitude": 76.3,
    "state": "Haryana",
    "district": "Kaithal",
    "village": "Guhla",
    "crop": "Paddy (Rice)",
    "residue_type": "Baled Straw",
    "condition": "Dry",
    "harvest_date": "2026-10-04",
    "status": "AVAILABLE",
    "created_at": "2026-10-06T14:30:00Z",
    "interest_count": 0
  },
  {
    "id": 16,
    "farmer_id": 20,
    "farmer_name": "Rajeshwar Bishnoi",
    "farmer_phone": "+91 98122 55400",
    "quantity_tonnes": 175.0,
    "asking_price_per_tonne": 1750.0,
    "latitude": 29.7,
    "longitude": 75.9,
    "state": "Haryana",
    "district": "Fatehabad",
    "village": "Tohana",
    "crop": "Cotton",
    "residue_type": "Cotton Stalks",
    "condition": "Dry",
    "harvest_date": "2026-10-01",
    "status": "AVAILABLE",
    "created_at": "2026-10-03T16:00:00Z",
    "interest_count": 0
  },
  {
    "id": 17,
    "farmer_id": 21,
    "farmer_name": "Sunil Dutt Tyagi",
    "farmer_phone": "+91 94165 44900",
    "quantity_tonnes": 150.0,
    "asking_price_per_tonne": 1800.0,
    "latitude": 29.24,
    "longitude": 77.01,
    "state": "Haryana",
    "district": "Panipat",
    "village": "Samalkha",
    "crop": "Maize",
    "residue_type": "Maize Stover",
    "condition": "Dry",
    "harvest_date": "2026-09-25",
    "status": "AVAILABLE",
    "created_at": "2026-10-01T09:45:00Z",
    "interest_count": 0
  },
  {
    "id": 18,
    "farmer_id": 22,
    "farmer_name": "Narender Singh Dahiya",
    "farmer_phone": "+91 98124 11899",
    "quantity_tonnes": 430.0,
    "asking_price_per_tonne": 2280.0,
    "latitude": 29.98,
    "longitude": 76.58,
    "state": "Haryana",
    "district": "Kurukshetra",
    "village": "Pehowa",
    "crop": "Paddy (Rice)",
    "residue_type": "Baled Straw",
    "condition": "Dry",
    "harvest_date": "2026-10-03",
    "status": "AVAILABLE",
    "created_at": "2026-10-05T15:20:00Z",
    "interest_count": 1
  },
  {
    "id": 19,
    "farmer_id": 23,
    "farmer_name": "Virender Kumar Malik",
    "farmer_phone": "+91 94162 77011",
    "quantity_tonnes": 260.0,
    "asking_price_per_tonne": 2550.0,
    "latitude": 30.48,
    "longitude": 77.13,
    "state": "Haryana",
    "district": "Ambala",
    "village": "Naraingarh",
    "crop": "Wheat",
    "residue_type": "Wheat Straw (Turi)",
    "condition": "Dry",
    "harvest_date": "2026-09-20",
    "status": "AVAILABLE",
    "created_at": "2026-10-02T11:00:00Z",
    "interest_count": 0
  },
  {
    "id": 20,
    "farmer_id": 24,
    "farmer_name": "Dharamvir Sihag",
    "farmer_phone": "+91 98126 33100",
    "quantity_tonnes": 310.0,
    "asking_price_per_tonne": 1800.0,
    "latitude": 29.45,
    "longitude": 74.65,
    "state": "Haryana",
    "district": "Sirsa",
    "village": "Ellenabad",
    "crop": "Cotton",
    "residue_type": "Cotton Stalks",
    "condition": "Dry",
    "harvest_date": "2026-10-02",
    "status": "AVAILABLE",
    "created_at": "2026-10-04T12:30:00Z",
    "interest_count": 0
  },
  {
    "id": 21,
    "farmer_id": 25,
    "farmer_name": "Devender Singh Punia",
    "farmer_phone": "+91 94160 88200",
    "quantity_tonnes": 390.0,
    "asking_price_per_tonne": 2400.0,
    "latitude": 29.1,
    "longitude": 75.96,
    "state": "Haryana",
    "district": "Hisar",
    "village": "Hansi",
    "crop": "Wheat",
    "residue_type": "Wheat Straw (Turi)",
    "condition": "Dry",
    "harvest_date": "2026-09-28",
    "status": "AVAILABLE",
    "created_at": "2026-10-05T08:45:00Z",
    "interest_count": 0
  },
  {
    "id": 22,
    "farmer_id": 6,
    "farmer_name": "Mahendra Pratap Shekhawat",
    "farmer_phone": "+91 94140 11244",
    "quantity_tonnes": 650.0,
    "asking_price_per_tonne": 1550.0,
    "latitude": 29.92,
    "longitude": 74.05,
    "state": "Rajasthan",
    "district": "Sri Ganganagar",
    "village": "Sadulshahar",
    "crop": "Mustard",
    "residue_type": "Mustard Husk & Stalks",
    "condition": "Dry",
    "harvest_date": "2026-08-25",
    "status": "AVAILABLE",
    "created_at": "2026-10-02T10:10:00Z",
    "interest_count": 1
  },
  {
    "id": 23,
    "farmer_id": 26,
    "farmer_name": "Om Prakash Meena",
    "farmer_phone": "+91 94145 99300",
    "quantity_tonnes": 380.0,
    "asking_price_per_tonne": 2400.0,
    "latitude": 29.18,
    "longitude": 74.77,
    "state": "Rajasthan",
    "district": "Hanumangarh",
    "village": "Nohar",
    "crop": "Wheat",
    "residue_type": "Wheat Straw (Turi)",
    "condition": "Dry",
    "harvest_date": "2026-09-22",
    "status": "AVAILABLE",
    "created_at": "2026-10-03T14:15:00Z",
    "interest_count": 0
  },
  {
    "id": 24,
    "farmer_id": 8,
    "farmer_name": "Jagdish Prasad Yadav",
    "farmer_phone": "+91 94144 33466",
    "quantity_tonnes": 240.0,
    "asking_price_per_tonne": 1600.0,
    "latitude": 27.888,
    "longitude": 76.282,
    "state": "Rajasthan",
    "district": "Alwar",
    "village": "Behror",
    "crop": "Mustard",
    "residue_type": "Mustard Husk",
    "condition": "Dry",
    "harvest_date": "2026-09-10",
    "status": "AVAILABLE",
    "created_at": "2026-09-28T09:00:00Z",
    "interest_count": 1
  },
  {
    "id": 25,
    "farmer_id": 9,
    "farmer_name": "Bhawani Singh Rathore",
    "farmer_phone": "+91 98295 44577",
    "quantity_tonnes": 510.0,
    "asking_price_per_tonne": 1500.0,
    "latitude": 24.92,
    "longitude": 76.28,
    "state": "Rajasthan",
    "district": "Kota",
    "village": "Sangod",
    "crop": "Sugarcane",
    "residue_type": "Sugarcane Bagasse & Trash",
    "condition": "Semi-Dry",
    "harvest_date": "2026-10-06",
    "status": "AVAILABLE",
    "created_at": "2026-10-07T12:00:00Z",
    "interest_count": 1
  },
  {
    "id": 26,
    "farmer_id": 27,
    "farmer_name": "Gordhan Ram Choudhary",
    "farmer_phone": "+91 94142 88100",
    "quantity_tonnes": 310.0,
    "asking_price_per_tonne": 1580.0,
    "latitude": 27.6,
    "longitude": 73.42,
    "state": "Rajasthan",
    "district": "Bikaner",
    "village": "Nokha",
    "crop": "Mustard",
    "residue_type": "Mustard Husk",
    "condition": "Dry",
    "harvest_date": "2026-09-14",
    "status": "AVAILABLE",
    "created_at": "2026-10-01T15:00:00Z",
    "interest_count": 0
  },
  {
    "id": 27,
    "farmer_id": 28,
    "farmer_name": "Ratan Lal Sharma",
    "farmer_phone": "+91 94148 22300",
    "quantity_tonnes": 280.0,
    "asking_price_per_tonne": 2350.0,
    "latitude": 26.9,
    "longitude": 77.29,
    "state": "Rajasthan",
    "district": "Bharatpur",
    "village": "Bayana",
    "crop": "Wheat",
    "residue_type": "Wheat Straw (Turi)",
    "condition": "Dry",
    "harvest_date": "2026-09-18",
    "status": "AVAILABLE",
    "created_at": "2026-10-02T13:20:00Z",
    "interest_count": 0
  },
  {
    "id": 28,
    "farmer_id": 29,
    "farmer_name": "Mahaveer Singh Shekhawat",
    "farmer_phone": "+91 98290 66400",
    "quantity_tonnes": 410.0,
    "asking_price_per_tonne": 2100.0,
    "latitude": 29.32,
    "longitude": 73.9,
    "state": "Rajasthan",
    "district": "Sri Ganganagar",
    "village": "Suratgarh",
    "crop": "Paddy (Rice)",
    "residue_type": "Baled Straw",
    "condition": "Dry",
    "harvest_date": "2026-10-04",
    "status": "AVAILABLE",
    "created_at": "2026-10-06T10:00:00Z",
    "interest_count": 0
  },
  {
    "id": 29,
    "farmer_id": 30,
    "farmer_name": "Ramkishan Gurjar",
    "farmer_phone": "+91 94149 11800",
    "quantity_tonnes": 220.0,
    "asking_price_per_tonne": 1750.0,
    "latitude": 27.17,
    "longitude": 75.72,
    "state": "Rajasthan",
    "district": "Jaipur",
    "village": "Chomu",
    "crop": "Maize",
    "residue_type": "Maize Stover",
    "condition": "Dry",
    "harvest_date": "2026-09-27",
    "status": "AVAILABLE",
    "created_at": "2026-10-04T16:15:00Z",
    "interest_count": 0
  },
  {
    "id": 30,
    "farmer_id": 31,
    "farmer_name": "Hardeep Singh Gill",
    "farmer_phone": "+91 98158 44000",
    "quantity_tonnes": 350.0,
    "asking_price_per_tonne": 2180.0,
    "latitude": 30.19,
    "longitude": 74.49,
    "state": "Punjab",
    "district": "Muktsar",
    "village": "Malout",
    "crop": "Paddy (Rice)",
    "residue_type": "Baled Straw",
    "condition": "Dry",
    "harvest_date": "2026-10-05",
    "status": "AVAILABLE",
    "created_at": "2026-10-07T11:00:00Z",
    "interest_count": 0
  }
];

export const MOCK_BUYERS = [
  {
    buyer_id: "BUYER-LDH-01",
    buyer_name: "EverGreen Bio-Energy & CBG Plant Ltd",
    buyer_type: "Bio-CNG / CBG Plant",
    state: "Punjab",
    district: "Ludhiana",
    latitude: 30.9010,
    longitude: 75.8573,
    offered_price: 2350.0,
    capacity_tonnes: 6500.0,
    is_available: true,
    contact_number: "+91 98765 11223",
    preferred_material: "Paddy Straw Bales",
    is_certified: true
  },
  {
    buyer_id: "BUYER-BTI-02",
    buyer_name: "Malwa Bio-Pellet & Briquette Works",
    buyer_type: "Biomass Pellet Manufacturer",
    state: "Punjab",
    district: "Bathinda",
    latitude: 30.2110,
    longitude: 74.9455,
    offered_price: 2100.0,
    capacity_tonnes: 3200.0,
    is_available: true,
    contact_number: "+91 98144 88711",
    preferred_material: "Cotton Residue & Paddy Straw",
    is_certified: true
  },
  {
    buyer_id: "BUYER-KRN-03",
    buyer_name: "Karnal Eco-Cardboard & Paper Mills",
    buyer_type: "Paper & Packaging Board Mill",
    state: "Haryana",
    district: "Karnal",
    latitude: 29.6857,
    longitude: 76.9905,
    offered_price: 2500.0,
    capacity_tonnes: 4500.0,
    is_available: true,
    contact_number: "+91 94164 22044",
    preferred_material: "Wheat Straw & Paddy Straw",
    is_certified: true
  },
  {
    buyer_id: "BUYER-SGN-04",
    buyer_name: "Shekhawat Bio-Refineries & Green Coal",
    buyer_type: "Bio-Coal & Bio-Refinery",
    state: "Rajasthan",
    district: "Sri Ganganagar",
    latitude: 29.9038,
    longitude: 73.8772,
    offered_price: 1750.0,
    capacity_tonnes: 5500.0,
    is_available: true,
    contact_number: "+91 94142 66488",
    preferred_material: "Mustard Husk & Cotton Residue",
    is_certified: true
  },
  {
    buyer_id: "BUYER-PNP-05",
    buyer_name: "Panipat Thermal Co-Firing Aggregation Hub",
    buyer_type: "Thermal Power Aggregator",
    state: "Haryana",
    district: "Panipat",
    latitude: 29.3909,
    longitude: 76.9635,
    offered_price: 2200.0,
    capacity_tonnes: 9500.0,
    is_available: true,
    contact_number: "+91 98124 33155",
    preferred_material: "Baled Straw & Sugarcane Trash",
    is_certified: true
  },
  {
    buyer_id: "BUYER-ALW-06",
    buyer_name: "Matsya Eco-Packaging & Board Ltd",
    buyer_type: "Eco-Packaging Manufacturer",
    state: "Rajasthan",
    district: "Alwar",
    latitude: 27.5530,
    longitude: 76.6346,
    offered_price: 1800.0,
    capacity_tonnes: 2800.0,
    is_available: true,
    contact_number: "+91 98292 77599",
    preferred_material: "Sugarcane Trash & Mustard Husk",
    is_certified: true
  }
];

export const MOCK_STATES = [
  { id: "punjab", name: "Punjab" },
  { id: "haryana", name: "Haryana" },
  { id: "rajasthan", name: "Rajasthan" }
];

export const MOCK_DISTRICTS = {
  punjab: [
    { id: "ludhiana", name: "Ludhiana" },
    { id: "bathinda", name: "Bathinda" },
    { id: "patiala", name: "Patiala" },
    { id: "amritsar", name: "Amritsar" },
    { id: "sangrur", name: "Sangrur" },
    { id: "jalandhar", name: "Jalandhar" },
    { id: "firozpur", name: "Firozpur" }
  ],
  haryana: [
    { id: "karnal", name: "Karnal" },
    { id: "kurukshetra", name: "Kurukshetra" },
    { id: "panipat", name: "Panipat" },
    { id: "ambala", name: "Ambala" },
    { id: "hisar", name: "Hisar" },
    { id: "rohtak", name: "Rohtak" }
  ],
  rajasthan: [
    { id: "sri_ganganagar", name: "Sri Ganganagar" },
    { id: "hanumangarh", name: "Hanumangarh" },
    { id: "alwar", name: "Alwar" },
    { id: "kota", name: "Kota" },
    { id: "bikaner", name: "Bikaner" }
  ]
};
